# Generated by Django 3.2.3 on 2021-06-10 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_city', models.CharField(max_length=255)),
                ('receiver_city', models.CharField(max_length=255)),
                ('manifest_code', models.CharField(default=items.models.generate_random_code, max_length=8, unique=True)),
                ('cmr', models.CharField(max_length=10, unique=True)),
                ('car_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_surname', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('sender_country', models.CharField(max_length=200)),
                ('sender_city', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_surname', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(blank=True, max_length=100)),
                ('receiver_country', models.CharField(max_length=200)),
                ('receiver_city', models.CharField(max_length=200)),
                ('receiver_address', models.CharField(blank=True, max_length=200)),
                ('receiver_number', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_currency', models.CharField(default='USD', max_length=20)),
                ('barcode', models.CharField(default=items.models.generate_barcode, max_length=200, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to='images/')),
                ('in_manifest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_number', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.manifest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
