# Generated by Django 3.2.3 on 2021-06-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_price_currency_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
