# Generated by Django 3.2.3 on 2021-06-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210617_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manifest_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.manifest'),
        ),
    ]
