# Generated by Django 3.2.3 on 2021-06-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_manifest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_manifest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
