# Generated by Django 3.2.3 on 2021-06-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_in_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manifest_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='items.manifest'),
        ),
    ]
