# Generated by Django 3.2.3 on 2021-06-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210627_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_manifest',
        ),
    ]
