# Generated by Django 3.2.3 on 2021-07-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210701_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barcode_image',
        ),
    ]
