# Generated by Django 3.2.3 on 2021-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_item_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='Personal Items', max_length=500),
        ),
    ]
