# Generated by Django 3.2.3 on 2021-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
