# Generated by Django 3.2.3 on 2021-07-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivered',
            field=models.BooleanField(null=True),
        ),
    ]
