# Generated by Django 3.2.3 on 2021-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
