# Generated by Django 3.2.3 on 2021-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_item_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
